package com.doctorandonuts.trackthis;

import android.util.Log;

import com.couchbase.lite.Context;
import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.Manager;
import com.couchbase.lite.android.AndroidContext;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by jgowing on 11/15/2016.
 */

public class MyDatabase {
    final String TAG = "CouchDB";

    private Database myDatabase = null;
    private String dbName = "trackthis";

    private Document document = null;
    private String documentName = "Trackers";

    public MyDatabase(android.content.Context context) {
        /** Create a manager */
        Manager manager;
        try {
            manager = new Manager(new AndroidContext(context), Manager.DEFAULT_OPTIONS);
            Log.d (TAG, "Manager created");
        } catch (IOException e) {
            Log.e(TAG, "Cannot create manager object");
            e.printStackTrace();
            return;
        }

        /** create a name for the database and make sure the name is legal */

        if (!Manager.isValidDatabaseName(dbName)) {
            Log.e(TAG, "Bad database name");
            return;
        }

        /** create a new database or get it if it already exists */
        try {
            myDatabase = manager.getDatabase(dbName);
            Log.d (TAG, "MyDatabase created");

        } catch (CouchbaseLiteException e) {
            Log.e(TAG, "Cannot get database");
            e.printStackTrace();
            return;
        }

        try {
           document = myDatabase.getDocument(documentName);
        } catch (Exception e) {
            Log.e(TAG, "Cannot get document");
            e.printStackTrace();
            return;
        }


        Map<String, Object> properties = new HashMap<>();
        properties.put("title", "Couchbase Mobile");
        properties.put("sdk", "Java");
        try {
            document.putProperties(properties);
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
        // Log the document ID (generated by the database) and properties
        Log.d(TAG, String.format("Document ID :: %s", document.getId()));
        Log.d(TAG, String.format("Learning %s with %s", document.getProperty("title"), document.getProperty("sdk")));


    }

    public Database getDatabase() {
        return myDatabase;
    }
}
